In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('resources\Covid_19_data.csv')

<>:1: SyntaxWarning: invalid escape sequence '\C'
<>:1: SyntaxWarning: invalid escape sequence '\C'
C:\Users\shivam\AppData\Local\Temp\ipykernel_28016\636003529.py:1: SyntaxWarning: invalid escape sequence '\C'
  df=pd.read_csv('resources\Covid_19_data.csv')

In [4]:
df.head()

        Date State       Region  Confirmed  Deaths  Recovered
0  4/29/2020   NaN  Afghanistan       1939      60        252
1  4/29/2020   NaN      Albania        766      30        455
2  4/29/2020   NaN      Algeria       3848     444       1702
3  4/29/2020   NaN      Andorra        743      42        423
4  4/29/2020   NaN       Angola         27       2          7

In [5]:
df.shape

(321, 6)

In [6]:
df.count()

Date         321
State        140
Region       321
Confirmed    321
Deaths       321
Recovered    321
dtype: int64

In [7]:
df.isnull().sum()

Date           0
State        181
Region         0
Confirmed      0
Deaths         0
Recovered      0
dtype: int64

#Q1 show the number of confirmed ,death and recovered cases in each region

In [8]:
df.head()

        Date State       Region  Confirmed  Deaths  Recovered
0  4/29/2020   NaN  Afghanistan       1939      60        252
1  4/29/2020   NaN      Albania        766      30        455
2  4/29/2020   NaN      Algeria       3848     444       1702
3  4/29/2020   NaN      Andorra        743      42        423
4  4/29/2020   NaN       Angola         27       2          7

In [9]:
df.groupby('Region').sum().head(10)

,Date,State,Confirmed,Deaths,Recovered
Region,,,,,
Afghanistan,4/29/2020,0,1939,60,252
Albania,4/29/2020,0,766,30,455
Algeria,4/29/2020,0,3848,444,1702
Andorra,4/29/2020,0,743,42,423
Angola,4/29/2020,0,27,2,7
Antigua and Barbuda,4/29/2020,0,24,3,11
Argentina,4/29/2020,0,4285,214,1192
Armenia,4/29/2020,0,1932,30,900
Australia,4/29/20204/29/20204/29/20204/29/20204/29/20204...,Australian Capital TerritoryNew South WalesNor...,6752,91,5715
Austria,4/29/2020,0,15402,580,12779

In [10]:
df.groupby('Region').agg({'Confirmed': 'sum', 'Recovered': 'sum'})

                    Confirmed  Recovered
Region
Afghanistan              1939        252
Albania                   766        455
Algeria                  3848       1702
Andorra                   743        423
Angola                     27          7
...                       ...        ...
West Bank and Gaza        344         71
Western Sahara              6          5
Yemen                       6          1
Zambia                     97         54
Zimbabwe                   32          5

[187 rows x 2 columns]

#Q2 remove all the records where confirmed cases is less than 10

In [11]:
df.head(2)
df.shape

(321, 6)

In [12]:
df[~(df['Confirmed']<10)]

          Date     State          Region  Confirmed  Deaths  Recovered
0    4/29/2020       NaN     Afghanistan       1939      60        252
1    4/29/2020       NaN         Albania        766      30        455
2    4/29/2020       NaN         Algeria       3848     444       1702
3    4/29/2020       NaN         Andorra        743      42        423
4    4/29/2020       NaN          Angola         27       2          7
..         ...       ...             ...        ...     ...        ...
316  4/29/2020   Wyoming              US        545       7          0
317  4/29/2020  Xinjiang  Mainland China         76       3         73
318  4/29/2020     Yukon          Canada         11       0          0
319  4/29/2020    Yunnan  Mainland China        185       2        181
320  4/29/2020  Zhejiang  Mainland China       1268       1       1263

[304 rows x 6 columns]

#Q3 In which region,maximum no. of confirmed cases were recorded

In [13]:
df.groupby('Region').Confirmed.sum().sort_values(ascending=False)

Region
US                  1039909
Spain                236899
Italy                203591
France               166543
UK                   166441
                     ...
Mauritania                8
Papua New Guinea          8
Bhutan                    7
Yemen                     6
Western Sahara            6
Name: Confirmed, Length: 187, dtype: int64

#Q4 show the region with the minimum no. of death cases

In [14]:
df.groupby('Region').Deaths.sum().sort_values(ascending=True)

Region
Cambodia                        0
Bhutan                          0
Dominica                        0
Central African Republic        0
Eritrea                         0
                            ...
France                      24121
Spain                       24275
UK                          26166
Italy                       27682
US                          60967
Name: Deaths, Length: 187, dtype: int64

#Q5  how many confirmed cases ,deaths and recovered casses were reported from india till 29,april,2020

In [15]:
df.head()

        Date State       Region  Confirmed  Deaths  Recovered
0  4/29/2020   NaN  Afghanistan       1939      60        252
1  4/29/2020   NaN      Albania        766      30        455
2  4/29/2020   NaN      Algeria       3848     444       1702
3  4/29/2020   NaN      Andorra        743      42        423
4  4/29/2020   NaN       Angola         27       2          7

In [16]:
df[df.Region =='India']

         Date State Region  Confirmed  Deaths  Recovered
74  4/29/2020   NaN  India      33062    1079       8437

#q6 sort the entire data according to the no, of confirmed cases

In [17]:
df.sort_values(by=['Confirmed'],ascending=True)

,Date,State,Region,Confirmed,Deaths,Recovered
284,4/29/2020,Recovered,Canada,0,0,20327
285,4/29/2020,Recovered,US,0,0,120720
203,4/29/2020,Diamond Princess cruise ship,Canada,0,1,0
289,4/29/2020,Saint Pierre and Miquelon,France,1,0,0
305,4/29/2020,Tibet,Mainland China,1,0,1
...,...,...,...,...,...,...
57,4/29/2020,NaN,France,165093,24087,48228
168,4/29/2020,NaN,UK,165221,26097,0
80,4/29/2020,NaN,Italy,203591,27682,71252
153,4/29/2020,NaN,Spain,236899,24275,132929
265,4/29/2020,New York,US,299691,23477,0

#q7 Sort the entire data with no. of recovered cases in the descending order

In [18]:
df.sort_values(by=['Recovered'],ascending=False)

          Date           State   Region  Confirmed  Deaths  Recovered
153  4/29/2020             NaN    Spain     236899   24275     132929
285  4/29/2020       Recovered       US          0       0     120720
61   4/29/2020             NaN  Germany     161539    6467     120400
76   4/29/2020             NaN     Iran      93657    5957      73791
80   4/29/2020             NaN    Italy     203591   27682      71252
..         ...             ...      ...        ...     ...        ...
290  4/29/2020    Saskatchewan   Canada        383       6          0
299  4/29/2020    South Dakota       US       2373      13          0
298  4/29/2020  South Carolina       US       5882     231          0
302  4/29/2020       Tennessee       US      10366     195          0
303  4/29/2020           Texas       US      27257     754          0

[321 rows x 6 columns]